"""empty message

Revision ID: 28111e175029
Revises: 3950042b21a4
Create Date: 2023-08-15 15:16:27.891727

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '28111e175029'
down_revision = '3950042b21a4'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('jobs', schema=None) as batch_op:
        batch_op.alter_column('job_url',
               existing_type=sa.VARCHAR(length=128),
               type_=sa.String(length=1000),
               existing_nullable=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('jobs', schema=None) as batch_op:
        batch_op.alter_column('job_url',
               existing_type=sa.String(length=1000),
               type_=sa.VARCHAR(length=128),
               existing_nullable=True)

    # ### end Alembic commands ###
