"""empty message

Revision ID: 597792da190b
Revises: 
Create Date: 2023-08-04 12:10:13.221513

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '597792da190b'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('jobs', schema=None) as batch_op:
        batch_op.drop_constraint('jobs_job_owner_fkey', type_='foreignkey')
        batch_op.create_foreign_key(None, 'users', ['job_owner'], ['id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('jobs', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key('jobs_job_owner_fkey', 'users', ['job_owner'], ['username'])

    # ### end Alembic commands ###
