"""empty message

Revision ID: 829d8861bcb6
Revises: 597792da190b
Create Date: 2023-08-04 13:13:27.009665

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '829d8861bcb6'
down_revision = '597792da190b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('jobs', schema=None) as batch_op:
        batch_op.alter_column('id',
               existing_type=sa.INTEGER(),
               type_=sa.String(length=500),
               existing_nullable=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('jobs', schema=None) as batch_op:
        batch_op.alter_column('id',
               existing_type=sa.String(length=500),
               type_=sa.INTEGER(),
               existing_nullable=False)

    # ### end Alembic commands ###
